version: "2"
networks:
  net:

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
  backend:
    build:
      context: backend
    networks:
      - net
  frontend:
    image: nginx
    volumes:
      - ./frontend/:/usr/share/nginx/html
    networks:
      - net
